export const EXECUTION_PLAN_STEP_TYPE = {
  INIT: 'INIT',
  FETCH: 'FETCH',
  REDUCE: 'REDUCE',
  COLLECT: 'COLLECT'
};

export const EXECUTION_PLAN_OPERATION_TYPE = {
  AND: 'AND',
  OR: 'OR',
  NONE: 'NONE'
};

export const EXECUTION_PLAN_OPERATE_ON = {
  ROOT: 'ROOT',
  PARENT: 'PARENT',
  PREVIOUS: 'PREVIOUS',
  NONE: 'NONE'
};

export default {
  EXECUTION_PLAN_STEP_TYPE,
  EXECUTION_PLAN_OPERATION_TYPE,
  EXECUTION_PLAN_OPERATE_ON
};